'type:ci':
  - .github/**/*
  - "*.json"
  - "*.yaml"
  - "*.cfg"
  - .clang-format
  - .gitignore
  - .prettierignore
'type:documentation':
  - docs/**/*
  - "**/*.md"
  - "**/*.rst"
  - "**/*.jpg"
  - "**/*.png"
  - "**/*.svg"
'type:common':
  - common/**/*
'type:control':
  - control/**/*
'type:evaluator':
  - evaluator/**/*
'type:launch':
  - launch/**/*
'type:localization':
  - localization/**/*
'type:map':
  - map/**/*
'type:perception':
  - perception/**/*
'type:planning':
  - planning/**/*
'type:sensing':
  - sensing/**/*
'type:simulator':
  - simulator/**/*
'type:system':
  - system/**/*
'type:tools':
  - tools/**/*
'type:vehicle':
  - vehicle/**/*
